version: '3.8'

services:
  node-api:
    build: ./node-app 
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
